import { spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";

const root = fileURLToPath(new URL("../../../", import.meta.url));

describe("generated SDK drift", () => {
  it("regenerating from the OpenAPI produces no diff (TS, Python and mock-model outputs)", () => {
    const r = spawnSync(process.execPath, ["scripts/generate-sdks.mjs", "--check"], {
      cwd: root,
      encoding: "utf8",
    });
    expect(r.stderr).toBe("");
    expect(r.status).toBe(0);
  });

  it("every generated file carries the DO NOT EDIT header", async () => {
    const { readFileSync } = await import("node:fs");
    for (const f of [
      "src/generated/types.ts",
      "src/generated/operations.ts",
      "src/generated/client.ts",
    ]) {
      expect(readFileSync(new URL(`../${f}`, import.meta.url), "utf8")).toMatch(
        /^\/\/ @generated by scripts\/generate-sdks\.mjs .* DO NOT EDIT\./,
      );
    }
  });
});
