# @generated by scripts/generate-sdks.mjs from packages/contracts/openapi/axis-v1.yaml (input sha256 789e410e6791ec9f). DO NOT EDIT.
# Regenerate with: node scripts/generate-sdks.mjs

from __future__ import annotations

from typing import Literal, cast

from ..transport_types import AsyncTransport, RequestOptions, SyncTransport
from .models import (
    AddRegistryKeyRequest,
    Approval,
    ApprovalPage,
    ApprovalStatus,
    BlueprintPage,
    BlueprintVersion,
    ClaimRegistryNamespaceRequest,
    DecideApprovalRequest,
    Decision,
    EvalRun,
    Explanation,
    GateDecision,
    GetUsageResponse,
    Identity,
    InstallMarketplaceListingRequest,
    InstallPreview,
    KillSwitch,
    KillSwitchRequest,
    ListAuditEventsResponse,
    ListKillSwitchesResponse,
    ListMarketplaceInstallsResponse,
    ListMarketplaceListingsResponse,
    ListRegistryKeysResponse,
    ListRegistryNamespacesResponse,
    ListRegistryVersionsResponse,
    ListRunEventsResponse,
    MarketplaceInstall,
    MarketplaceListing,
    PolicyPack,
    PolicyPackPage,
    PreviewMarketplaceInstallRequest,
    ProcessState,
    PublishBlueprintVersionRequest,
    PublishPolicyPackRequest,
    PublishRegistryBlueprintRequest,
    RegistryKey,
    RegistryNamespace,
    RegistryVersion,
    ResolvedBlueprint,
    Run,
    RunPage,
    SignalRunRequest,
    SignalRunResponse,
    StartEvalRunRequest,
    StartRunRequest,
    TestPolicyRequest,
    UninstallMarketplaceListingResponse,
    VerifyAuditChainRequest,
    VerifyAuditChainResponse,
    YankRegistryVersionRequest,
    YankRegistryVersionResponse,
)
from .operations import OPERATIONS

__all__ = ["AsyncGeneratedApi", "GeneratedApi"]


class GeneratedApi:
    """One method per operationId (synchronous)."""

    def __init__(self, transport: SyncTransport) -> None:
        self._t = transport

    def list_blueprints(
        self,
        *,
        limit: int | None = None,
        cursor: str | None = None,
        options: RequestOptions | None = None,
    ) -> BlueprintPage:
        """GET /blueprints: List blueprints"""
        return cast("BlueprintPage", self._t.call(
            OPERATIONS["listBlueprints"],
            path={},
            query={"limit": limit, "cursor": cursor},
            body=None,
            idempotency_key=None,
            options=options,
        ))

    def publish_blueprint_version(
        self,
        *,
        body: PublishBlueprintVersionRequest,
        idempotency_key: str | None = None,
        options: RequestOptions | None = None,
    ) -> BlueprintVersion:
        """POST /blueprints: Validate and publish a blueprint version (immutable once published)"""
        return cast("BlueprintVersion", self._t.call(
            OPERATIONS["publishBlueprintVersion"],
            path={},
            query={},
            body=body,
            idempotency_key=idempotency_key,
            options=options,
        ))

    def get_blueprint_version(
        self,
        *,
        name: str,
        version: str,
        options: RequestOptions | None = None,
    ) -> BlueprintVersion:
        """GET /blueprints/{name}/versions/{version}: Get one blueprint version"""
        return cast("BlueprintVersion", self._t.call(
            OPERATIONS["getBlueprintVersion"],
            path={"name": name, "version": version},
            query={},
            body=None,
            idempotency_key=None,
            options=options,
        ))

    def list_runs(
        self,
        *,
        limit: int | None = None,
        cursor: str | None = None,
        state: ProcessState | None = None,
        blueprint: str | None = None,
        options: RequestOptions | None = None,
    ) -> RunPage:
        """GET /runs: List runs"""
        return cast("RunPage", self._t.call(
            OPERATIONS["listRuns"],
            path={},
            query={"limit": limit, "cursor": cursor, "state": state, "blueprint": blueprint},
            body=None,
            idempotency_key=None,
            options=options,
        ))

    def start_run(
        self,
        *,
        body: StartRunRequest,
        idempotency_key: str | None = None,
        options: RequestOptions | None = None,
    ) -> Run:
        """POST /runs: Start a run (spawns the init process as a durable workflow)"""
        return cast("Run", self._t.call(
            OPERATIONS["startRun"],
            path={},
            query={},
            body=body,
            idempotency_key=idempotency_key,
            options=options,
        ))

    def get_run(
        self,
        *,
        run_id: str,
        options: RequestOptions | None = None,
    ) -> Run:
        """GET /runs/{runId}: Get a run"""
        return cast("Run", self._t.call(
            OPERATIONS["getRun"],
            path={"runId": run_id},
            query={},
            body=None,
            idempotency_key=None,
            options=options,
        ))

    def signal_run(
        self,
        *,
        run_id: str,
        body: SignalRunRequest,
        idempotency_key: str | None = None,
        options: RequestOptions | None = None,
    ) -> SignalRunResponse:
        """POST /runs/{runId}/signals: Send a signal (PAUSE, RESUME, TERM, KILL, INTERRUPT) to a process in the run"""
        return cast("SignalRunResponse", self._t.call(
            OPERATIONS["signalRun"],
            path={"runId": run_id},
            query={},
            body=body,
            idempotency_key=idempotency_key,
            options=options,
        ))

    def list_run_events(
        self,
        *,
        run_id: str,
        after_sequence: int | None = None,
        limit: int | None = None,
        options: RequestOptions | None = None,
    ) -> ListRunEventsResponse:
        """GET /runs/{runId}/events: Read the run's append-only event log (basis for replay)"""
        return cast("ListRunEventsResponse", self._t.call(
            OPERATIONS["listRunEvents"],
            path={"runId": run_id},
            query={"after_sequence": after_sequence, "limit": limit},
            body=None,
            idempotency_key=None,
            options=options,
        ))

    def list_approvals(
        self,
        *,
        status: ApprovalStatus | None = None,
        limit: int | None = None,
        cursor: str | None = None,
        options: RequestOptions | None = None,
    ) -> ApprovalPage:
        """GET /approvals: List approvals"""
        return cast("ApprovalPage", self._t.call(
            OPERATIONS["listApprovals"],
            path={},
            query={"status": status, "limit": limit, "cursor": cursor},
            body=None,
            idempotency_key=None,
            options=options,
        ))

    def decide_approval(
        self,
        *,
        approval_id: str,
        body: DecideApprovalRequest,
        idempotency_key: str | None = None,
        options: RequestOptions | None = None,
    ) -> Approval:
        """POST /approvals/{approvalId}/decision: Approve or reject a pending approval"""
        return cast("Approval", self._t.call(
            OPERATIONS["decideApproval"],
            path={"approvalId": approval_id},
            query={},
            body=body,
            idempotency_key=idempotency_key,
            options=options,
        ))

    def list_policy_packs(
        self,
        *,
        limit: int | None = None,
        cursor: str | None = None,
        options: RequestOptions | None = None,
    ) -> PolicyPackPage:
        """GET /policies: List policy packs"""
        return cast("PolicyPackPage", self._t.call(
            OPERATIONS["listPolicyPacks"],
            path={},
            query={"limit": limit, "cursor": cursor},
            body=None,
            idempotency_key=None,
            options=options,
        ))

    def publish_policy_pack(
        self,
        *,
        body: PublishPolicyPackRequest,
        options: RequestOptions | None = None,
    ) -> PolicyPack:
        """POST /policies: Validate, compile to Rego and publish a policy pack version"""
        return cast("PolicyPack", self._t.call(
            OPERATIONS["publishPolicyPack"],
            path={},
            query={},
            body=body,
            idempotency_key=None,
            options=options,
        ))

    def test_policy(
        self,
        *,
        body: TestPolicyRequest,
        options: RequestOptions | None = None,
    ) -> GateDecision:
        """POST /policies:test: Evaluate a hypothetical request against a policy pack without executing anything"""
        return cast("GateDecision", self._t.call(
            OPERATIONS["testPolicy"],
            path={},
            query={},
            body=body,
            idempotency_key=None,
            options=options,
        ))

    def list_audit_events(
        self,
        *,
        limit: int | None = None,
        cursor: str | None = None,
        trace_id: str | None = None,
        decision: Decision | None = None,
        from_seq: int | None = None,
        options: RequestOptions | None = None,
    ) -> ListAuditEventsResponse:
        """GET /audit/events: Query the tenant's audit log"""
        return cast("ListAuditEventsResponse", self._t.call(
            OPERATIONS["listAuditEvents"],
            path={},
            query={"limit": limit, "cursor": cursor, "trace_id": trace_id, "decision": decision, "from_seq": from_seq},
            body=None,
            idempotency_key=None,
            options=options,
        ))

    def explain_run(
        self,
        *,
        run_id: str,
        options: RequestOptions | None = None,
    ) -> Explanation:
        """GET /runs/{runId}/explanation: Explain a run from its audit trail (AGIL; read-only, deterministic)"""
        return cast("Explanation", self._t.call(
            OPERATIONS["explainRun"],
            path={"runId": run_id},
            query={},
            body=None,
            idempotency_key=None,
            options=options,
        ))

    def explain_audit_event(
        self,
        *,
        seq: int,
        options: RequestOptions | None = None,
    ) -> Explanation:
        """GET /audit/events/{seq}/explanation: Explain one audited decision or approval step (AGIL; read-only, deterministic)"""
        return cast("Explanation", self._t.call(
            OPERATIONS["explainAuditEvent"],
            path={"seq": seq},
            query={},
            body=None,
            idempotency_key=None,
            options=options,
        ))

    def verify_audit_chain(
        self,
        *,
        body: VerifyAuditChainRequest | None = None,
        options: RequestOptions | None = None,
    ) -> VerifyAuditChainResponse:
        """POST /audit/verify: Verify hash-chain integrity over a range"""
        return cast("VerifyAuditChainResponse", self._t.call(
            OPERATIONS["verifyAuditChain"],
            path={},
            query={},
            body=body,
            idempotency_key=None,
            options=options,
        ))

    def list_kill_switches(
        self,
        *,
        options: RequestOptions | None = None,
    ) -> ListKillSwitchesResponse:
        """GET /kill-switches: List engaged kill-switches visible to the tenant"""
        return cast("ListKillSwitchesResponse", self._t.call(
            OPERATIONS["listKillSwitches"],
            path={},
            query={},
            body=None,
            idempotency_key=None,
            options=options,
        ))

    def set_kill_switch(
        self,
        *,
        body: KillSwitchRequest,
        options: RequestOptions | None = None,
    ) -> KillSwitch:
        """PUT /kill-switches: Engage or release a tenant, agent or tool kill-switch (effective < 1 s)"""
        return cast("KillSwitch", self._t.call(
            OPERATIONS["setKillSwitch"],
            path={},
            query={},
            body=body,
            idempotency_key=None,
            options=options,
        ))

    def get_usage(
        self,
        *,
        from_: str,
        to: str,
        group_by: Literal["meter", "model", "blueprint", "day"] | None = None,
        options: RequestOptions | None = None,
    ) -> GetUsageResponse:
        """GET /usage: Metered usage by meter and period"""
        return cast("GetUsageResponse", self._t.call(
            OPERATIONS["getUsage"],
            path={},
            query={"from": from_, "to": to, "group_by": group_by},
            body=None,
            idempotency_key=None,
            options=options,
        ))

    def start_eval_run(
        self,
        *,
        body: StartEvalRunRequest,
        idempotency_key: str | None = None,
        options: RequestOptions | None = None,
    ) -> EvalRun:
        """POST /evals/runs: Run an eval suite against a blueprint version"""
        return cast("EvalRun", self._t.call(
            OPERATIONS["startEvalRun"],
            path={},
            query={},
            body=body,
            idempotency_key=idempotency_key,
            options=options,
        ))

    def get_me(
        self,
        *,
        options: RequestOptions | None = None,
    ) -> Identity:
        """GET /me: Who the credential belongs to (tenant, member, role, credential kind and scopes)"""
        return cast("Identity", self._t.call(
            OPERATIONS["getMe"],
            path={},
            query={},
            body=None,
            idempotency_key=None,
            options=options,
        ))

    def get_approval(
        self,
        *,
        approval_id: str,
        options: RequestOptions | None = None,
    ) -> Approval:
        """GET /approvals/{approvalId}: Get one approval"""
        return cast("Approval", self._t.call(
            OPERATIONS["getApproval"],
            path={"approvalId": approval_id},
            query={},
            body=None,
            idempotency_key=None,
            options=options,
        ))

    def activate_policy_pack(
        self,
        *,
        version_id: str,
        options: RequestOptions | None = None,
    ) -> PolicyPack:
        """POST /policies/{versionId}/activate: Make a published policy pack version the tenant's active version of that pack (the Risk Kernel enforces it from then on)"""
        return cast("PolicyPack", self._t.call(
            OPERATIONS["activatePolicyPack"],
            path={"versionId": version_id},
            query={},
            body=None,
            idempotency_key=None,
            options=options,
        ))

    def list_registry_namespaces(
        self,
        *,
        options: RequestOptions | None = None,
    ) -> ListRegistryNamespacesResponse:
        """GET /registry/namespaces: List the registry namespaces your tenant owns"""
        return cast("ListRegistryNamespacesResponse", self._t.call(
            OPERATIONS["listRegistryNamespaces"],
            path={},
            query={},
            body=None,
            idempotency_key=None,
            options=options,
        ))

    def claim_registry_namespace(
        self,
        *,
        body: ClaimRegistryNamespaceRequest,
        idempotency_key: str | None = None,
        options: RequestOptions | None = None,
    ) -> RegistryNamespace:
        """POST /registry/namespaces: Claim a registry namespace for your tenant (admin)"""
        return cast("RegistryNamespace", self._t.call(
            OPERATIONS["claimRegistryNamespace"],
            path={},
            query={},
            body=body,
            idempotency_key=idempotency_key,
            options=options,
        ))

    def list_registry_keys(
        self,
        *,
        namespace: str,
        options: RequestOptions | None = None,
    ) -> ListRegistryKeysResponse:
        """GET /registry/namespaces/{namespace}/keys: List a namespace's publisher keys (public halves only)"""
        return cast("ListRegistryKeysResponse", self._t.call(
            OPERATIONS["listRegistryKeys"],
            path={"namespace": namespace},
            query={},
            body=None,
            idempotency_key=None,
            options=options,
        ))

    def add_registry_key(
        self,
        *,
        namespace: str,
        body: AddRegistryKeyRequest,
        idempotency_key: str | None = None,
        options: RequestOptions | None = None,
    ) -> RegistryKey:
        """POST /registry/namespaces/{namespace}/keys: Register an Ed25519 publisher public key for a namespace (admin)"""
        return cast("RegistryKey", self._t.call(
            OPERATIONS["addRegistryKey"],
            path={"namespace": namespace},
            query={},
            body=body,
            idempotency_key=idempotency_key,
            options=options,
        ))

    def publish_registry_blueprint(
        self,
        *,
        namespace: str,
        body: PublishRegistryBlueprintRequest,
        idempotency_key: str | None = None,
        options: RequestOptions | None = None,
    ) -> RegistryVersion:
        """POST /registry/namespaces/{namespace}/blueprints: Publish a signed blueprint version with its provenance attestation (immutable; verified before it is stored)"""
        return cast("RegistryVersion", self._t.call(
            OPERATIONS["publishRegistryBlueprint"],
            path={"namespace": namespace},
            query={},
            body=body,
            idempotency_key=idempotency_key,
            options=options,
        ))

    def list_registry_versions(
        self,
        *,
        namespace: str,
        name: str,
        options: RequestOptions | None = None,
    ) -> ListRegistryVersionsResponse:
        """GET /registry/blueprints/{namespace}/{name}/versions: List the versions of a registry blueprint with their status"""
        return cast("ListRegistryVersionsResponse", self._t.call(
            OPERATIONS["listRegistryVersions"],
            path={"namespace": namespace, "name": name},
            query={},
            body=None,
            idempotency_key=None,
            options=options,
        ))

    def yank_registry_version(
        self,
        *,
        namespace: str,
        name: str,
        version: str,
        body: YankRegistryVersionRequest,
        options: RequestOptions | None = None,
    ) -> YankRegistryVersionResponse:
        """POST /registry/blueprints/{namespace}/{name}/versions/{version}/yank: Yank a version so it stops resolving (admin; recorded, never deleted)"""
        return cast("YankRegistryVersionResponse", self._t.call(
            OPERATIONS["yankRegistryVersion"],
            path={"namespace": namespace, "name": name, "version": version},
            query={},
            body=body,
            idempotency_key=None,
            options=options,
        ))

    def resolve_registry_blueprint(
        self,
        *,
        ref: str,
        options: RequestOptions | None = None,
    ) -> ResolvedBlueprint:
        """GET /registry/resolve: Resolve `namespace/name@range` to the highest non-yanked version and VERIFY it (hash, signature, provenance) before returning it"""
        return cast("ResolvedBlueprint", self._t.call(
            OPERATIONS["resolveRegistryBlueprint"],
            path={},
            query={"ref": ref},
            body=None,
            idempotency_key=None,
            options=options,
        ))

    def list_marketplace_listings(
        self,
        *,
        q: str | None = None,
        category: str | None = None,
        options: RequestOptions | None = None,
    ) -> ListMarketplaceListingsResponse:
        """GET /marketplace/listings: Browse the marketplace catalog (listed, security-reviewed blueprints only)"""
        return cast("ListMarketplaceListingsResponse", self._t.call(
            OPERATIONS["listMarketplaceListings"],
            path={},
            query={"q": q, "category": category},
            body=None,
            idempotency_key=None,
            options=options,
        ))

    def get_marketplace_listing(
        self,
        *,
        namespace: str,
        name: str,
        options: RequestOptions | None = None,
    ) -> MarketplaceListing:
        """GET /marketplace/listings/{namespace}/{name}: Get one marketplace listing"""
        return cast("MarketplaceListing", self._t.call(
            OPERATIONS["getMarketplaceListing"],
            path={"namespace": namespace, "name": name},
            query={},
            body=None,
            idempotency_key=None,
            options=options,
        ))

    def preview_marketplace_install(
        self,
        *,
        body: PreviewMarketplaceInstallRequest,
        options: RequestOptions | None = None,
    ) -> InstallPreview:
        """POST /marketplace/installs/preview: Preview an install - findings, requested permissions, the diff against your tenant baseline and the consent digest (admin)"""
        return cast("InstallPreview", self._t.call(
            OPERATIONS["previewMarketplaceInstall"],
            path={},
            query={},
            body=body,
            idempotency_key=None,
            options=options,
        ))

    def list_marketplace_installs(
        self,
        *,
        options: RequestOptions | None = None,
    ) -> ListMarketplaceInstallsResponse:
        """GET /marketplace/installs: List your tenant's installs"""
        return cast("ListMarketplaceInstallsResponse", self._t.call(
            OPERATIONS["listMarketplaceInstalls"],
            path={},
            query={},
            body=None,
            idempotency_key=None,
            options=options,
        ))

    def install_marketplace_listing(
        self,
        *,
        body: InstallMarketplaceListingRequest,
        idempotency_key: str | None = None,
        options: RequestOptions | None = None,
    ) -> MarketplaceInstall:
        """POST /marketplace/installs: Install a listing, pinned to a version and content hash, with consent to the exact permission diff you previewed (admin)"""
        return cast("MarketplaceInstall", self._t.call(
            OPERATIONS["installMarketplaceListing"],
            path={},
            query={},
            body=body,
            idempotency_key=idempotency_key,
            options=options,
        ))

    def uninstall_marketplace_listing(
        self,
        *,
        namespace: str,
        name: str,
        options: RequestOptions | None = None,
    ) -> UninstallMarketplaceListingResponse:
        """POST /marketplace/installs/{namespace}/{name}/uninstall: Uninstall a listing (admin)"""
        return cast("UninstallMarketplaceListingResponse", self._t.call(
            OPERATIONS["uninstallMarketplaceListing"],
            path={"namespace": namespace, "name": name},
            query={},
            body=None,
            idempotency_key=None,
            options=options,
        ))


class AsyncGeneratedApi:
    """One method per operationId (asynchronous)."""

    def __init__(self, transport: AsyncTransport) -> None:
        self._t = transport

    async def list_blueprints(
        self,
        *,
        limit: int | None = None,
        cursor: str | None = None,
        options: RequestOptions | None = None,
    ) -> BlueprintPage:
        """GET /blueprints: List blueprints"""
        return cast("BlueprintPage", await self._t.call(
            OPERATIONS["listBlueprints"],
            path={},
            query={"limit": limit, "cursor": cursor},
            body=None,
            idempotency_key=None,
            options=options,
        ))

    async def publish_blueprint_version(
        self,
        *,
        body: PublishBlueprintVersionRequest,
        idempotency_key: str | None = None,
        options: RequestOptions | None = None,
    ) -> BlueprintVersion:
        """POST /blueprints: Validate and publish a blueprint version (immutable once published)"""
        return cast("BlueprintVersion", await self._t.call(
            OPERATIONS["publishBlueprintVersion"],
            path={},
            query={},
            body=body,
            idempotency_key=idempotency_key,
            options=options,
        ))

    async def get_blueprint_version(
        self,
        *,
        name: str,
        version: str,
        options: RequestOptions | None = None,
    ) -> BlueprintVersion:
        """GET /blueprints/{name}/versions/{version}: Get one blueprint version"""
        return cast("BlueprintVersion", await self._t.call(
            OPERATIONS["getBlueprintVersion"],
            path={"name": name, "version": version},
            query={},
            body=None,
            idempotency_key=None,
            options=options,
        ))

    async def list_runs(
        self,
        *,
        limit: int | None = None,
        cursor: str | None = None,
        state: ProcessState | None = None,
        blueprint: str | None = None,
        options: RequestOptions | None = None,
    ) -> RunPage:
        """GET /runs: List runs"""
        return cast("RunPage", await self._t.call(
            OPERATIONS["listRuns"],
            path={},
            query={"limit": limit, "cursor": cursor, "state": state, "blueprint": blueprint},
            body=None,
            idempotency_key=None,
            options=options,
        ))

    async def start_run(
        self,
        *,
        body: StartRunRequest,
        idempotency_key: str | None = None,
        options: RequestOptions | None = None,
    ) -> Run:
        """POST /runs: Start a run (spawns the init process as a durable workflow)"""
        return cast("Run", await self._t.call(
            OPERATIONS["startRun"],
            path={},
            query={},
            body=body,
            idempotency_key=idempotency_key,
            options=options,
        ))

    async def get_run(
        self,
        *,
        run_id: str,
        options: RequestOptions | None = None,
    ) -> Run:
        """GET /runs/{runId}: Get a run"""
        return cast("Run", await self._t.call(
            OPERATIONS["getRun"],
            path={"runId": run_id},
            query={},
            body=None,
            idempotency_key=None,
            options=options,
        ))

    async def signal_run(
        self,
        *,
        run_id: str,
        body: SignalRunRequest,
        idempotency_key: str | None = None,
        options: RequestOptions | None = None,
    ) -> SignalRunResponse:
        """POST /runs/{runId}/signals: Send a signal (PAUSE, RESUME, TERM, KILL, INTERRUPT) to a process in the run"""
        return cast("SignalRunResponse", await self._t.call(
            OPERATIONS["signalRun"],
            path={"runId": run_id},
            query={},
            body=body,
            idempotency_key=idempotency_key,
            options=options,
        ))

    async def list_run_events(
        self,
        *,
        run_id: str,
        after_sequence: int | None = None,
        limit: int | None = None,
        options: RequestOptions | None = None,
    ) -> ListRunEventsResponse:
        """GET /runs/{runId}/events: Read the run's append-only event log (basis for replay)"""
        return cast("ListRunEventsResponse", await self._t.call(
            OPERATIONS["listRunEvents"],
            path={"runId": run_id},
            query={"after_sequence": after_sequence, "limit": limit},
            body=None,
            idempotency_key=None,
            options=options,
        ))

    async def list_approvals(
        self,
        *,
        status: ApprovalStatus | None = None,
        limit: int | None = None,
        cursor: str | None = None,
        options: RequestOptions | None = None,
    ) -> ApprovalPage:
        """GET /approvals: List approvals"""
        return cast("ApprovalPage", await self._t.call(
            OPERATIONS["listApprovals"],
            path={},
            query={"status": status, "limit": limit, "cursor": cursor},
            body=None,
            idempotency_key=None,
            options=options,
        ))

    async def decide_approval(
        self,
        *,
        approval_id: str,
        body: DecideApprovalRequest,
        idempotency_key: str | None = None,
        options: RequestOptions | None = None,
    ) -> Approval:
        """POST /approvals/{approvalId}/decision: Approve or reject a pending approval"""
        return cast("Approval", await self._t.call(
            OPERATIONS["decideApproval"],
            path={"approvalId": approval_id},
            query={},
            body=body,
            idempotency_key=idempotency_key,
            options=options,
        ))

    async def list_policy_packs(
        self,
        *,
        limit: int | None = None,
        cursor: str | None = None,
        options: RequestOptions | None = None,
    ) -> PolicyPackPage:
        """GET /policies: List policy packs"""
        return cast("PolicyPackPage", await self._t.call(
            OPERATIONS["listPolicyPacks"],
            path={},
            query={"limit": limit, "cursor": cursor},
            body=None,
            idempotency_key=None,
            options=options,
        ))

    async def publish_policy_pack(
        self,
        *,
        body: PublishPolicyPackRequest,
        options: RequestOptions | None = None,
    ) -> PolicyPack:
        """POST /policies: Validate, compile to Rego and publish a policy pack version"""
        return cast("PolicyPack", await self._t.call(
            OPERATIONS["publishPolicyPack"],
            path={},
            query={},
            body=body,
            idempotency_key=None,
            options=options,
        ))

    async def test_policy(
        self,
        *,
        body: TestPolicyRequest,
        options: RequestOptions | None = None,
    ) -> GateDecision:
        """POST /policies:test: Evaluate a hypothetical request against a policy pack without executing anything"""
        return cast("GateDecision", await self._t.call(
            OPERATIONS["testPolicy"],
            path={},
            query={},
            body=body,
            idempotency_key=None,
            options=options,
        ))

    async def list_audit_events(
        self,
        *,
        limit: int | None = None,
        cursor: str | None = None,
        trace_id: str | None = None,
        decision: Decision | None = None,
        from_seq: int | None = None,
        options: RequestOptions | None = None,
    ) -> ListAuditEventsResponse:
        """GET /audit/events: Query the tenant's audit log"""
        return cast("ListAuditEventsResponse", await self._t.call(
            OPERATIONS["listAuditEvents"],
            path={},
            query={"limit": limit, "cursor": cursor, "trace_id": trace_id, "decision": decision, "from_seq": from_seq},
            body=None,
            idempotency_key=None,
            options=options,
        ))

    async def explain_run(
        self,
        *,
        run_id: str,
        options: RequestOptions | None = None,
    ) -> Explanation:
        """GET /runs/{runId}/explanation: Explain a run from its audit trail (AGIL; read-only, deterministic)"""
        return cast("Explanation", await self._t.call(
            OPERATIONS["explainRun"],
            path={"runId": run_id},
            query={},
            body=None,
            idempotency_key=None,
            options=options,
        ))

    async def explain_audit_event(
        self,
        *,
        seq: int,
        options: RequestOptions | None = None,
    ) -> Explanation:
        """GET /audit/events/{seq}/explanation: Explain one audited decision or approval step (AGIL; read-only, deterministic)"""
        return cast("Explanation", await self._t.call(
            OPERATIONS["explainAuditEvent"],
            path={"seq": seq},
            query={},
            body=None,
            idempotency_key=None,
            options=options,
        ))

    async def verify_audit_chain(
        self,
        *,
        body: VerifyAuditChainRequest | None = None,
        options: RequestOptions | None = None,
    ) -> VerifyAuditChainResponse:
        """POST /audit/verify: Verify hash-chain integrity over a range"""
        return cast("VerifyAuditChainResponse", await self._t.call(
            OPERATIONS["verifyAuditChain"],
            path={},
            query={},
            body=body,
            idempotency_key=None,
            options=options,
        ))

    async def list_kill_switches(
        self,
        *,
        options: RequestOptions | None = None,
    ) -> ListKillSwitchesResponse:
        """GET /kill-switches: List engaged kill-switches visible to the tenant"""
        return cast("ListKillSwitchesResponse", await self._t.call(
            OPERATIONS["listKillSwitches"],
            path={},
            query={},
            body=None,
            idempotency_key=None,
            options=options,
        ))

    async def set_kill_switch(
        self,
        *,
        body: KillSwitchRequest,
        options: RequestOptions | None = None,
    ) -> KillSwitch:
        """PUT /kill-switches: Engage or release a tenant, agent or tool kill-switch (effective < 1 s)"""
        return cast("KillSwitch", await self._t.call(
            OPERATIONS["setKillSwitch"],
            path={},
            query={},
            body=body,
            idempotency_key=None,
            options=options,
        ))

    async def get_usage(
        self,
        *,
        from_: str,
        to: str,
        group_by: Literal["meter", "model", "blueprint", "day"] | None = None,
        options: RequestOptions | None = None,
    ) -> GetUsageResponse:
        """GET /usage: Metered usage by meter and period"""
        return cast("GetUsageResponse", await self._t.call(
            OPERATIONS["getUsage"],
            path={},
            query={"from": from_, "to": to, "group_by": group_by},
            body=None,
            idempotency_key=None,
            options=options,
        ))

    async def start_eval_run(
        self,
        *,
        body: StartEvalRunRequest,
        idempotency_key: str | None = None,
        options: RequestOptions | None = None,
    ) -> EvalRun:
        """POST /evals/runs: Run an eval suite against a blueprint version"""
        return cast("EvalRun", await self._t.call(
            OPERATIONS["startEvalRun"],
            path={},
            query={},
            body=body,
            idempotency_key=idempotency_key,
            options=options,
        ))

    async def get_me(
        self,
        *,
        options: RequestOptions | None = None,
    ) -> Identity:
        """GET /me: Who the credential belongs to (tenant, member, role, credential kind and scopes)"""
        return cast("Identity", await self._t.call(
            OPERATIONS["getMe"],
            path={},
            query={},
            body=None,
            idempotency_key=None,
            options=options,
        ))

    async def get_approval(
        self,
        *,
        approval_id: str,
        options: RequestOptions | None = None,
    ) -> Approval:
        """GET /approvals/{approvalId}: Get one approval"""
        return cast("Approval", await self._t.call(
            OPERATIONS["getApproval"],
            path={"approvalId": approval_id},
            query={},
            body=None,
            idempotency_key=None,
            options=options,
        ))

    async def activate_policy_pack(
        self,
        *,
        version_id: str,
        options: RequestOptions | None = None,
    ) -> PolicyPack:
        """POST /policies/{versionId}/activate: Make a published policy pack version the tenant's active version of that pack (the Risk Kernel enforces it from then on)"""
        return cast("PolicyPack", await self._t.call(
            OPERATIONS["activatePolicyPack"],
            path={"versionId": version_id},
            query={},
            body=None,
            idempotency_key=None,
            options=options,
        ))

    async def list_registry_namespaces(
        self,
        *,
        options: RequestOptions | None = None,
    ) -> ListRegistryNamespacesResponse:
        """GET /registry/namespaces: List the registry namespaces your tenant owns"""
        return cast("ListRegistryNamespacesResponse", await self._t.call(
            OPERATIONS["listRegistryNamespaces"],
            path={},
            query={},
            body=None,
            idempotency_key=None,
            options=options,
        ))

    async def claim_registry_namespace(
        self,
        *,
        body: ClaimRegistryNamespaceRequest,
        idempotency_key: str | None = None,
        options: RequestOptions | None = None,
    ) -> RegistryNamespace:
        """POST /registry/namespaces: Claim a registry namespace for your tenant (admin)"""
        return cast("RegistryNamespace", await self._t.call(
            OPERATIONS["claimRegistryNamespace"],
            path={},
            query={},
            body=body,
            idempotency_key=idempotency_key,
            options=options,
        ))

    async def list_registry_keys(
        self,
        *,
        namespace: str,
        options: RequestOptions | None = None,
    ) -> ListRegistryKeysResponse:
        """GET /registry/namespaces/{namespace}/keys: List a namespace's publisher keys (public halves only)"""
        return cast("ListRegistryKeysResponse", await self._t.call(
            OPERATIONS["listRegistryKeys"],
            path={"namespace": namespace},
            query={},
            body=None,
            idempotency_key=None,
            options=options,
        ))

    async def add_registry_key(
        self,
        *,
        namespace: str,
        body: AddRegistryKeyRequest,
        idempotency_key: str | None = None,
        options: RequestOptions | None = None,
    ) -> RegistryKey:
        """POST /registry/namespaces/{namespace}/keys: Register an Ed25519 publisher public key for a namespace (admin)"""
        return cast("RegistryKey", await self._t.call(
            OPERATIONS["addRegistryKey"],
            path={"namespace": namespace},
            query={},
            body=body,
            idempotency_key=idempotency_key,
            options=options,
        ))

    async def publish_registry_blueprint(
        self,
        *,
        namespace: str,
        body: PublishRegistryBlueprintRequest,
        idempotency_key: str | None = None,
        options: RequestOptions | None = None,
    ) -> RegistryVersion:
        """POST /registry/namespaces/{namespace}/blueprints: Publish a signed blueprint version with its provenance attestation (immutable; verified before it is stored)"""
        return cast("RegistryVersion", await self._t.call(
            OPERATIONS["publishRegistryBlueprint"],
            path={"namespace": namespace},
            query={},
            body=body,
            idempotency_key=idempotency_key,
            options=options,
        ))

    async def list_registry_versions(
        self,
        *,
        namespace: str,
        name: str,
        options: RequestOptions | None = None,
    ) -> ListRegistryVersionsResponse:
        """GET /registry/blueprints/{namespace}/{name}/versions: List the versions of a registry blueprint with their status"""
        return cast("ListRegistryVersionsResponse", await self._t.call(
            OPERATIONS["listRegistryVersions"],
            path={"namespace": namespace, "name": name},
            query={},
            body=None,
            idempotency_key=None,
            options=options,
        ))

    async def yank_registry_version(
        self,
        *,
        namespace: str,
        name: str,
        version: str,
        body: YankRegistryVersionRequest,
        options: RequestOptions | None = None,
    ) -> YankRegistryVersionResponse:
        """POST /registry/blueprints/{namespace}/{name}/versions/{version}/yank: Yank a version so it stops resolving (admin; recorded, never deleted)"""
        return cast("YankRegistryVersionResponse", await self._t.call(
            OPERATIONS["yankRegistryVersion"],
            path={"namespace": namespace, "name": name, "version": version},
            query={},
            body=body,
            idempotency_key=None,
            options=options,
        ))

    async def resolve_registry_blueprint(
        self,
        *,
        ref: str,
        options: RequestOptions | None = None,
    ) -> ResolvedBlueprint:
        """GET /registry/resolve: Resolve `namespace/name@range` to the highest non-yanked version and VERIFY it (hash, signature, provenance) before returning it"""
        return cast("ResolvedBlueprint", await self._t.call(
            OPERATIONS["resolveRegistryBlueprint"],
            path={},
            query={"ref": ref},
            body=None,
            idempotency_key=None,
            options=options,
        ))

    async def list_marketplace_listings(
        self,
        *,
        q: str | None = None,
        category: str | None = None,
        options: RequestOptions | None = None,
    ) -> ListMarketplaceListingsResponse:
        """GET /marketplace/listings: Browse the marketplace catalog (listed, security-reviewed blueprints only)"""
        return cast("ListMarketplaceListingsResponse", await self._t.call(
            OPERATIONS["listMarketplaceListings"],
            path={},
            query={"q": q, "category": category},
            body=None,
            idempotency_key=None,
            options=options,
        ))

    async def get_marketplace_listing(
        self,
        *,
        namespace: str,
        name: str,
        options: RequestOptions | None = None,
    ) -> MarketplaceListing:
        """GET /marketplace/listings/{namespace}/{name}: Get one marketplace listing"""
        return cast("MarketplaceListing", await self._t.call(
            OPERATIONS["getMarketplaceListing"],
            path={"namespace": namespace, "name": name},
            query={},
            body=None,
            idempotency_key=None,
            options=options,
        ))

    async def preview_marketplace_install(
        self,
        *,
        body: PreviewMarketplaceInstallRequest,
        options: RequestOptions | None = None,
    ) -> InstallPreview:
        """POST /marketplace/installs/preview: Preview an install - findings, requested permissions, the diff against your tenant baseline and the consent digest (admin)"""
        return cast("InstallPreview", await self._t.call(
            OPERATIONS["previewMarketplaceInstall"],
            path={},
            query={},
            body=body,
            idempotency_key=None,
            options=options,
        ))

    async def list_marketplace_installs(
        self,
        *,
        options: RequestOptions | None = None,
    ) -> ListMarketplaceInstallsResponse:
        """GET /marketplace/installs: List your tenant's installs"""
        return cast("ListMarketplaceInstallsResponse", await self._t.call(
            OPERATIONS["listMarketplaceInstalls"],
            path={},
            query={},
            body=None,
            idempotency_key=None,
            options=options,
        ))

    async def install_marketplace_listing(
        self,
        *,
        body: InstallMarketplaceListingRequest,
        idempotency_key: str | None = None,
        options: RequestOptions | None = None,
    ) -> MarketplaceInstall:
        """POST /marketplace/installs: Install a listing, pinned to a version and content hash, with consent to the exact permission diff you previewed (admin)"""
        return cast("MarketplaceInstall", await self._t.call(
            OPERATIONS["installMarketplaceListing"],
            path={},
            query={},
            body=body,
            idempotency_key=idempotency_key,
            options=options,
        ))

    async def uninstall_marketplace_listing(
        self,
        *,
        namespace: str,
        name: str,
        options: RequestOptions | None = None,
    ) -> UninstallMarketplaceListingResponse:
        """POST /marketplace/installs/{namespace}/{name}/uninstall: Uninstall a listing (admin)"""
        return cast("UninstallMarketplaceListingResponse", await self._t.call(
            OPERATIONS["uninstallMarketplaceListing"],
            path={"namespace": namespace, "name": name},
            query={},
            body=None,
            idempotency_key=None,
            options=options,
        ))
