# @generated by scripts/generate-sdks.mjs from packages/contracts/openapi/axis-v1.yaml (input sha256 b62c5727759355ff). DO NOT EDIT.
# Regenerate with: node scripts/generate-sdks.mjs

from __future__ import annotations

from typing import Any, Literal, NotRequired, TypedDict


type Pid = str


type ProcessState = Literal["spawn", "ready", "running", "waiting", "suspended", "terminated"]


type Signal = Literal["PAUSE", "RESUME", "TERM", "KILL", "INTERRUPT"]


type Decision = Literal["ALLOW", "DENY", "REQUIRE_APPROVAL", "ALLOW_WITH_REDACTION"]


type ApprovalStatus = Literal["pending", "approved", "rejected", "expired", "escalated"]


type Meter = Literal["tokens", "runtime_seconds", "tool_executions", "voice_minutes", "storage_gb_hours", "marketplace_installs"]


class Problem(TypedDict):
    type: str
    title: str
    status: int
    code: NotRequired[Literal["unauthenticated", "forbidden", "policy_denied", "not_found", "conflict", "validation_failed", "rate_limited", "budget_exceeded", "internal"]]
    detail: NotRequired[str]
    trace_id: NotRequired[str]


class ValidationProblemBodyErrorsItem(TypedDict):
    path: str
    keyword: NotRequired[str]
    message: str


class ValidationProblemBody(TypedDict):
    type: str
    title: str
    status: int
    code: NotRequired[Literal["unauthenticated", "forbidden", "policy_denied", "not_found", "conflict", "validation_failed", "rate_limited", "budget_exceeded", "internal"]]
    detail: NotRequired[str]
    trace_id: NotRequired[str]
    errors: list[ValidationProblemBodyErrorsItem]


class BlueprintVersion(TypedDict):
    name: str
    version: str
    risk_level: Literal["minimal", "limited", "high"]
    content_hash: NotRequired[str]
    signature: NotRequired[str | None]
    created_at: str
    abl: AblDocument


class BlueprintPage(TypedDict):
    items: list[BlueprintVersion]
    next_cursor: NotRequired[str | None]


class RunBlueprint(TypedDict):
    name: str
    version: str


class Run(TypedDict):
    id: str
    init_pid: NotRequired[Pid]
    blueprint: RunBlueprint
    state: ProcessState
    exit_reason: NotRequired[str | None]
    trace_id: NotRequired[str]
    created_at: str
    finished_at: NotRequired[str | None]


class RunPage(TypedDict):
    items: list[Run]
    next_cursor: NotRequired[str | None]


class RunEvent(TypedDict):
    sequence: int
    type: str
    pid: Pid
    at: str
    audit_event_id: NotRequired[str]
    data: NotRequired[dict[str, Any]]


class GateDecision(TypedDict):
    decision: Decision
    policy_version: str
    reason: NotRequired[str]
    matched_rule_ids: NotRequired[list[str]]
    redact_fields: NotRequired[list[str]]


class Approval(TypedDict):
    id: str
    status: ApprovalStatus
    run_id: str
    pid: NotRequired[Pid]
    action: NotRequired[str]
    roles: NotRequired[list[str]]
    requested_at: str
    sla_deadline: str
    decided_by: NotRequired[str | None]
    decided_at: NotRequired[str | None]
    comment: NotRequired[str | None]


class ApprovalPage(TypedDict):
    items: list[Approval]
    next_cursor: NotRequired[str | None]


class PolicyPack(TypedDict):
    name: str
    version: str
    content_hash: NotRequired[str]
    created_at: str


class PolicyPackPage(TypedDict):
    items: list[PolicyPack]
    next_cursor: NotRequired[str | None]


class KillSwitchRequest(TypedDict):
    scope: Literal["tenant", "agent", "tool"]
    target: NotRequired[str]
    engaged: bool
    reason: NotRequired[str]


class KillSwitch(TypedDict):
    scope: Literal["global", "tenant", "agent", "tool"]
    target: NotRequired[str | None]
    engaged: bool
    reason: NotRequired[str | None]
    updated_at: str


class EvalRun(TypedDict):
    id: str
    suite: str
    status: Literal["queued", "running", "passed", "failed", "errored"]
    score: NotRequired[float | None]
    threshold: NotRequired[float | None]


class ExplanationStepsItem(TypedDict):
    n: int
    kind: Literal["request", "evaluation", "outcome", "context", "run"]
    text: str
    audit_event_id: NotRequired[str]
    seq: NotRequired[int]


class ExplanationDecisionRefsItem(TypedDict):
    audit_event_id: str
    seq: int
    ts: NotRequired[str]
    decision: Decision
    enforcement_point: str
    action: str
    policy_version: str
    policy_packs: NotRequired[list[str]]
    gate: Literal["kill_switch", "policy_rule", "default_deny", "amount_cap", "target_cap", "budget", "rate_limit", "staleness", "approval", "audit_unavailable", "invalid_request", "evaluation_failure", "admin", "other"]
    rule_ids: list[str]
    gate_id: NotRequired[str]
    kill_switch_scope: NotRequired[Literal["global", "tenant", "agent", "tool"]]
    approval_id: NotRequired[str]
    reason: str


class ExplanationRemediationItem(TypedDict):
    kind: Literal["release_kill_switch", "add_policy_rule", "review_policy_rule", "adjust_request", "raise_limit", "wait", "decide_approval", "retry", "contact_operator", "inspect"]
    text: str
    hint: NotRequired[str]


class Explanation(TypedDict):
    summary: str
    steps: list[ExplanationStepsItem]
    decision_refs: list[ExplanationDecisionRefsItem]
    remediation: list[ExplanationRemediationItem]
    narrative: NotRequired[str]


class AuditEventActor(TypedDict):
    type: Literal["human", "agent", "system"]
    id: str
    pid: NotRequired[str]


class AuditEventBlueprint(TypedDict):
    name: str
    version: str


class AuditEvent(TypedDict):
    schema_version: Literal[1]
    id: str
    tenant_id: str
    seq: int
    ts: str
    trace_id: str
    actor: AuditEventActor
    blueprint: AuditEventBlueprint
    policy_version: str
    enforcement_point: Literal["tool_call", "mcp_call", "model_call", "memory_write", "message_send", "code_exec", "browser_exec", "lifecycle", "admin"]
    action: str
    decision: Literal["ALLOW", "DENY", "REQUIRE_APPROVAL", "ALLOW_WITH_REDACTION"]
    reason: NotRequired[str]
    inputs_hash: str
    outputs_hash: str
    prev_hash: str
    hash: str


type AblDocument = dict[str, Any]


type PolicyDocument = dict[str, Any]


class PublishBlueprintVersionRequest(TypedDict):
    abl: AblDocument


class StartRunRequestBlueprint(TypedDict):
    name: str
    version: str


class StartRunRequest(TypedDict):
    blueprint: StartRunRequestBlueprint
    input: NotRequired[dict[str, Any]]


class SignalRunRequest(TypedDict):
    pid: NotRequired[Pid]
    signal: Signal
    reason: NotRequired[str]


class SignalRunResponse(TypedDict):
    pid: Pid
    state: ProcessState


class ListRunEventsResponse(TypedDict):
    items: list[RunEvent]
    next_cursor: NotRequired[str | None]


class DecideApprovalRequest(TypedDict):
    decision: Literal["approve", "reject"]
    comment: NotRequired[str]


class PublishPolicyPackRequest(TypedDict):
    policy: PolicyDocument


class TestPolicyRequestRequest(TypedDict):
    enforcement_point: str
    action: NotRequired[str]
    context: dict[str, Any]


class TestPolicyRequest(TypedDict):
    policy: PolicyDocument
    request: TestPolicyRequestRequest


class ListAuditEventsResponse(TypedDict):
    items: list[AuditEvent]
    next_cursor: NotRequired[str | None]


class VerifyAuditChainRequest(TypedDict):
    from_seq: NotRequired[int]
    to_seq: NotRequired[int]


class VerifyAuditChainResponse(TypedDict):
    ok: bool
    verified: int
    broken_at_seq: NotRequired[int]
    reason: NotRequired[str]


class ListKillSwitchesResponse(TypedDict):
    items: list[KillSwitch]


class GetUsageResponseItemsItem(TypedDict):
    meter: Meter
    quantity: float
    unit: str
    group: NotRequired[str]


class GetUsageResponse(TypedDict):
    items: list[GetUsageResponseItemsItem]


class StartEvalRunRequestBlueprint(TypedDict):
    name: str
    version: str


class StartEvalRunRequest(TypedDict):
    suite: str
    blueprint: StartEvalRunRequestBlueprint
