# @generated by scripts/generate-sdks.mjs from packages/contracts/openapi/axis-v1.yaml (input sha256 5ef5aec9da501fb0). DO NOT EDIT.
# Regenerate with: node scripts/generate-sdks.mjs

from __future__ import annotations

from typing import Any, Literal, NotRequired, TypedDict


type Pid = str


type ProcessState = Literal["spawn", "ready", "running", "waiting", "suspended", "terminated"]


type Signal = Literal["PAUSE", "RESUME", "TERM", "KILL", "INTERRUPT"]


type Decision = Literal["ALLOW", "DENY", "REQUIRE_APPROVAL", "ALLOW_WITH_REDACTION"]


type ApprovalStatus = Literal["pending", "approved", "rejected", "expired", "escalated"]


type Meter = Literal["tokens", "runtime_seconds", "tool_executions", "voice_minutes", "storage_gb_hours", "marketplace_installs"]


class Problem(TypedDict):
    type: str
    title: str
    status: int
    code: NotRequired[Literal["unauthenticated", "forbidden", "policy_denied", "not_found", "conflict", "validation_failed", "rate_limited", "budget_exceeded", "internal"]]
    detail: NotRequired[str]
    trace_id: NotRequired[str]


class ValidationProblemBodyErrorsItem(TypedDict):
    path: str
    keyword: NotRequired[str]
    message: str


class ValidationProblemBody(TypedDict):
    type: str
    title: str
    status: int
    code: NotRequired[Literal["unauthenticated", "forbidden", "policy_denied", "not_found", "conflict", "validation_failed", "rate_limited", "budget_exceeded", "internal"]]
    detail: NotRequired[str]
    trace_id: NotRequired[str]
    errors: list[ValidationProblemBodyErrorsItem]


class BlueprintVersion(TypedDict):
    name: str
    version: str
    risk_level: Literal["minimal", "limited", "high"]
    content_hash: NotRequired[str]
    signature: NotRequired[str | None]
    created_at: str
    abl: AblDocument


class BlueprintPage(TypedDict):
    items: list[BlueprintVersion]
    next_cursor: NotRequired[str | None]


class RunBlueprint(TypedDict):
    name: str
    version: str


class Run(TypedDict):
    id: str
    init_pid: NotRequired[Pid]
    blueprint: RunBlueprint
    state: ProcessState
    exit_reason: NotRequired[str | None]
    trace_id: NotRequired[str]
    created_at: str
    finished_at: NotRequired[str | None]


class RunPage(TypedDict):
    items: list[Run]
    next_cursor: NotRequired[str | None]


class RunEvent(TypedDict):
    sequence: int
    type: str
    pid: Pid
    at: str
    audit_event_id: NotRequired[str]
    data: NotRequired[dict[str, Any]]


class GateDecision(TypedDict):
    decision: Decision
    policy_version: str
    reason: NotRequired[str]
    matched_rule_ids: NotRequired[list[str]]
    redact_fields: NotRequired[list[str]]


class Approval(TypedDict):
    id: str
    status: ApprovalStatus
    run_id: str
    pid: NotRequired[Pid]
    action: NotRequired[str]
    roles: NotRequired[list[str]]
    requested_at: str
    sla_deadline: str
    decided_by: NotRequired[str | None]
    decided_at: NotRequired[str | None]
    comment: NotRequired[str | None]


class ApprovalPage(TypedDict):
    items: list[Approval]
    next_cursor: NotRequired[str | None]


class PolicyPack(TypedDict):
    name: str
    version: str
    content_hash: NotRequired[str]
    created_at: str
    version_id: NotRequired[str]
    active: NotRequired[bool]


class PolicyPackPage(TypedDict):
    items: list[PolicyPack]
    next_cursor: NotRequired[str | None]


class KillSwitchRequest(TypedDict):
    scope: Literal["tenant", "agent", "tool"]
    target: NotRequired[str]
    engaged: bool
    reason: NotRequired[str]


class KillSwitch(TypedDict):
    scope: Literal["global", "tenant", "agent", "tool"]
    target: NotRequired[str | None]
    engaged: bool
    reason: NotRequired[str | None]
    updated_at: str


class EvalRunCost(TypedDict):
    agent_usd: NotRequired[str]
    judge_usd: NotRequired[str]
    total_usd: NotRequired[str]
    tokens: NotRequired[int]
    judge_tokens: NotRequired[int]


class EvalRun(TypedDict):
    id: str
    suite: str
    status: Literal["queued", "running", "passed", "failed", "errored"]
    score: NotRequired[float | None]
    threshold: NotRequired[float | None]
    blueprint: NotRequired[EvalBlueprintRef]
    mode: NotRequired[Literal["ci", "manual"]]
    scores: NotRequired[EvalScores]
    sample_size: NotRequired[int]
    pending_human: NotRequired[int]
    cost: NotRequired[EvalRunCost]
    runner_id: NotRequired[str | None]
    requested_by: NotRequired[str]
    provenance: NotRequired[dict[str, Any] | None]
    created_at: NotRequired[str]
    started_at: NotRequired[str | None]
    finished_at: NotRequired[str | None]
    failure_reason: NotRequired[str | None]
    record_hash: NotRequired[str | None]


class EvalBlueprintRef(TypedDict):
    namespace: NotRequired[str | None]
    name: str
    version: str
    content_hash: str


class EvalScores(TypedDict):
    status: Literal["complete", "pending_human"]
    overall: float | None
    per_grader: dict[str, Any]
    per_case: dict[str, Any]
    passed: bool | None
    failures: list[str]
    ungraded: int


class EvalCaseResultGradesItem(TypedDict):
    grader_id: str
    kind: Literal["deterministic", "model", "human"]
    status: Literal["scored", "ungraded", "pending", "error"]
    score: float
    detail: NotRequired[str]
    provenance: NotRequired[dict[str, Any]]


class EvalCaseResult(TypedDict):
    case_id: str
    status: str
    attempts: NotRequired[int]
    seed: NotRequired[int]
    error: NotRequired[str | None]
    score: NotRequired[float | None]
    output: NotRequired[str | None]
    grades: list[EvalCaseResultGradesItem]
    trace: NotRequired[dict[str, Any] | None]


class EvalRunDetailCost(TypedDict):
    agent_usd: NotRequired[str]
    judge_usd: NotRequired[str]
    total_usd: NotRequired[str]
    tokens: NotRequired[int]
    judge_tokens: NotRequired[int]


class EvalRunDetail(TypedDict):
    id: str
    suite: str
    status: Literal["queued", "running", "passed", "failed", "errored"]
    score: NotRequired[float | None]
    threshold: NotRequired[float | None]
    blueprint: NotRequired[EvalBlueprintRef]
    mode: NotRequired[Literal["ci", "manual"]]
    scores: NotRequired[EvalScores]
    sample_size: NotRequired[int]
    pending_human: NotRequired[int]
    cost: NotRequired[EvalRunDetailCost]
    runner_id: NotRequired[str | None]
    requested_by: NotRequired[str]
    provenance: NotRequired[dict[str, Any] | None]
    created_at: NotRequired[str]
    started_at: NotRequired[str | None]
    finished_at: NotRequired[str | None]
    failure_reason: NotRequired[str | None]
    record_hash: NotRequired[str | None]
    case_results: list[EvalCaseResult]


class EvalRunPage(TypedDict):
    items: list[EvalRun]
    next_cursor: str | None


class EvalGateResultReasonsItem(TypedDict):
    code: str
    suite_ref: NotRequired[str]
    message: str


class EvalGateResultRunsItem(TypedDict):
    suite_ref: str
    run_id: NotRequired[str | None]
    overall: NotRequired[float | None]
    required_threshold: float
    sample_size: NotRequired[int | None]
    finished_at: NotRequired[str | None]
    baseline_run_id: NotRequired[str | None]
    delta: NotRequired[float | None]
    regression: NotRequired[bool | None]
    p_value: NotRequired[float | None]


class EvalGateResult(TypedDict):
    allowed: bool
    blueprint: EvalBlueprintRef
    reasons: list[EvalGateResultReasonsItem]
    runs: list[EvalGateResultRunsItem]
    checked_at: str


class EvalComparisonSignificance(TypedDict):
    test: NotRequired[str]
    method: NotRequired[Literal["exact", "monte_carlo", "degenerate"]]
    n: NotRequired[int]
    mean_diff: NotRequired[float]
    p_value: NotRequired[float]
    alpha: NotRequired[float]
    significant: NotRequired[bool]


class EvalComparison(TypedDict):
    comparable: bool
    baseline_run_id: str
    delta: NotRequired[float | None]
    per_grader_delta: NotRequired[dict[str, Any]]
    tolerance: float
    regression: bool
    blocking: bool
    significance: NotRequired[EvalComparisonSignificance]


class EvalCase(TypedDict):
    id: str
    input: Any
    expected: NotRequired[Any]
    tags: NotRequired[list[str]]
    metadata: NotRequired[dict[str, Any]]


class EvalDataset(TypedDict):
    name: str
    version: int
    ref: str
    description: NotRequired[str | None]
    phi: bool
    redacted: NotRequired[bool]
    case_count: int
    content_hash: str
    version_hash: NotRequired[str]
    created_at: str
    created_by: NotRequired[str]


class EvalDatasetVersion(TypedDict):
    name: str
    version: int
    ref: str
    description: NotRequired[str | None]
    phi: bool
    redacted: NotRequired[bool]
    case_count: int
    content_hash: str
    version_hash: NotRequired[str]
    created_at: str
    created_by: NotRequired[str]
    cases: list[EvalCase]


class EvalGrader(TypedDict):
    id: str
    kind: Literal["deterministic", "model", "human"]
    weight: NotRequired[float]
    config: NotRequired[dict[str, Any]]
    min_mean: NotRequired[float | None]


class EvalSuite(TypedDict):
    ref: str
    name: str
    version: str
    dataset_ref: str
    dataset_hash: str
    graders: list[EvalGrader]
    pass_threshold: float
    min_case_score: NotRequired[float | None]
    settings: NotRequired[dict[str, Any]]
    tolerance: float
    required_for_release: NotRequired[bool]
    applies_to: NotRequired[list[str]]
    min_samples: NotRequired[int | None]
    max_age_days: NotRequired[int]
    regression_requires_significance: NotRequired[bool]
    alpha: NotRequired[float]
    suite_hash: str
    created_at: str
    created_by: NotRequired[str]


class EvalBaseline(TypedDict):
    blueprint_name: str
    suite_ref: str
    seq: int
    run_id: str
    overall: float
    record_hash: NotRequired[str]
    set_by: str
    at: str


class EvalReviewTaskGradesItem(TypedDict):
    reviewer: str
    score: float
    comment: str
    at: str
    adjudication: bool


class EvalReviewTaskResolution(TypedDict):
    score: NotRequired[float]
    method: NotRequired[Literal["single", "agreed", "adjudicated"]]


class EvalReviewTask(TypedDict):
    id: str
    run_id: str
    suite_ref: str
    case_id: str
    grader_id: str
    rubric: str
    blueprint: NotRequired[EvalBlueprintRef]
    case_input: NotRequired[Any]
    case_output: NotRequired[str | None]
    case_expected: NotRequired[Any]
    state: Literal["open", "claimed", "needs_adjudication", "resolved"]
    created_at: NotRequired[str]
    sla_deadline: str
    sla_breached: bool
    double_grade: NotRequired[bool]
    claimed_by: NotRequired[str | None]
    claim_expires_at: NotRequired[str | None]
    grades: NotRequired[list[EvalReviewTaskGradesItem]]
    resolution: NotRequired[EvalReviewTaskResolution | None]


class EvalSamplingConfig(TypedDict):
    id: str
    blueprint_name: str
    suite_ref: str
    rate: float
    max_per_hour: int
    redaction: Literal["phi", "always"]
    enabled: bool
    alert_threshold: NotRequired[float | None]
    updated_by: NotRequired[str]
    updated_at: NotRequired[str]


class EvalOnlineSummaryWindow(TypedDict):
    count: int
    mean: NotRequired[float | None]


class EvalOnlineSummaryRecentItem(TypedDict):
    at: str
    score: float
    blueprint_version: NotRequired[str]
    trace_id: NotRequired[str | None]


class EvalOnlineSummary(TypedDict):
    sampling_id: str
    blueprint_name: str
    suite_ref: str
    enabled: bool
    count: int
    mean: NotRequired[float | None]
    window: EvalOnlineSummaryWindow
    alert_threshold: NotRequired[float | None]
    alerting: bool
    recent: list[EvalOnlineSummaryRecentItem]


class EvalRunner(TypedDict):
    runner_id: str
    description: NotRequired[str | None]
    registered_by: NotRequired[str]
    registered_at: str
    revoked_at: NotRequired[str | None]
    revoked_by: NotRequired[str | None]


class ExplanationStepsItem(TypedDict):
    n: int
    kind: Literal["request", "evaluation", "outcome", "context", "run"]
    text: str
    audit_event_id: NotRequired[str]
    seq: NotRequired[int]


class ExplanationDecisionRefsItem(TypedDict):
    audit_event_id: str
    seq: int
    ts: NotRequired[str]
    decision: Decision
    enforcement_point: str
    action: str
    policy_version: str
    policy_packs: NotRequired[list[str]]
    gate: Literal["kill_switch", "policy_rule", "default_deny", "amount_cap", "target_cap", "budget", "rate_limit", "staleness", "approval", "audit_unavailable", "invalid_request", "evaluation_failure", "admin", "other"]
    rule_ids: list[str]
    gate_id: NotRequired[str]
    kill_switch_scope: NotRequired[Literal["global", "tenant", "agent", "tool"]]
    approval_id: NotRequired[str]
    reason: str


class ExplanationRemediationItem(TypedDict):
    kind: Literal["release_kill_switch", "add_policy_rule", "review_policy_rule", "adjust_request", "raise_limit", "wait", "decide_approval", "retry", "contact_operator", "inspect"]
    text: str
    hint: NotRequired[str]


class Explanation(TypedDict):
    summary: str
    steps: list[ExplanationStepsItem]
    decision_refs: list[ExplanationDecisionRefsItem]
    remediation: list[ExplanationRemediationItem]
    narrative: NotRequired[str]


class IdentityTenant(TypedDict):
    id: str
    name: NotRequired[str]
    region: NotRequired[str]


class IdentityMember(TypedDict):
    id: str
    email: NotRequired[str]
    display_name: NotRequired[str]
    role: Literal["owner", "admin", "builder", "operator", "auditor", "billing", "viewer"]


class IdentityCredential(TypedDict):
    kind: Literal["session", "api_key"]
    scopes: NotRequired[list[str]]


class Identity(TypedDict):
    tenant: IdentityTenant
    member: IdentityMember
    credential: IdentityCredential


class RegistryNamespace(TypedDict):
    namespace: str
    public: NotRequired[bool]
    created_at: NotRequired[str]


class RegistryKey(TypedDict):
    key_id: str
    public_key: str
    valid_from: str
    valid_until: NotRequired[str | None]
    revoked_at: NotRequired[str | None]
    revoke_reason: NotRequired[str | None]


class RegistrySignature(TypedDict):
    key_id: str
    signed_at: str
    sig: str


class DsseEnvelopeSignaturesItem(TypedDict):
    keyid: str
    sig: str


class DsseEnvelope(TypedDict):
    payloadType: str
    payload: str
    signatures: list[DsseEnvelopeSignaturesItem]


class RegistryVersion(TypedDict):
    namespace: str
    name: str
    version: str
    content_hash: str
    risk_level: Literal["minimal", "limited", "high"]
    signature: RegistrySignature
    published_at: str
    published_by: NotRequired[str]
    state: NotRequired[Literal["active", "deprecated", "yanked"]]
    state_reason: NotRequired[str | None]


class ResolvedBlueprintVerification(TypedDict):
    key_id: str
    builder: NotRequired[str]
    source_ref: NotRequired[str]
    compiler_version: NotRequired[str]


class ResolvedBlueprint(TypedDict):
    namespace: str
    name: str
    version: str
    content_hash: str
    risk_level: Literal["minimal", "limited", "high"]
    signature: RegistrySignature
    published_at: str
    published_by: NotRequired[str]
    state: NotRequired[Literal["active", "deprecated", "yanked"]]
    state_reason: NotRequired[str | None]
    abl: AblDocument
    provenance: DsseEnvelope
    verification: ResolvedBlueprintVerification


class MarketplaceListingLatest(TypedDict):
    version: NotRequired[str]
    content_hash: NotRequired[str]
    risk_level: NotRequired[str]
    max_severity: NotRequired[str]


class MarketplaceListing(TypedDict):
    namespace: str
    name: str
    title: str
    summary: str
    categories: list[str]
    publisher: NotRequired[str]
    latest: NotRequired[MarketplaceListingLatest | None]
    versions: list[str]


class Capability(TypedDict):
    key: str
    level: float


class InstallPreviewFindingsItem(TypedDict):
    id: str
    severity: str
    path: NotRequired[str]
    message: str


class InstallPreviewDiffAddedItem(TypedDict):
    key: str
    change: Literal["new", "raised"]
    level: float
    previous_level: NotRequired[float | None]


class InstallPreviewDiffRemovedItem(TypedDict):
    key: str
    level: float
    new_level: NotRequired[float | None]


class InstallPreviewDiff(TypedDict):
    added: list[InstallPreviewDiffAddedItem]
    removed: list[InstallPreviewDiffRemovedItem]
    widening: bool


class InstallPreview(TypedDict):
    namespace: str
    name: str
    version: str
    content_hash: str
    risk_level: str
    max_severity: NotRequired[str]
    findings: list[InstallPreviewFindingsItem]
    capabilities: list[Capability]
    diff: InstallPreviewDiff
    consent_digest: str


class MarketplaceInstall(TypedDict):
    id: str
    namespace: str
    name: str
    version: str
    content_hash: str
    state: Literal["active", "flagged", "uninstalled"]
    granted: list[Capability]
    consented_by: NotRequired[str]
    consented_at: NotRequired[str]
    flag_reason: NotRequired[str | None]


class AuditEventActor(TypedDict):
    type: Literal["human", "agent", "system"]
    id: str
    pid: NotRequired[str]


class AuditEventBlueprint(TypedDict):
    name: str
    version: str


class AuditEvent(TypedDict):
    schema_version: Literal[1]
    id: str
    tenant_id: str
    seq: int
    ts: str
    trace_id: str
    actor: AuditEventActor
    blueprint: AuditEventBlueprint
    policy_version: str
    enforcement_point: Literal["tool_call", "mcp_call", "model_call", "memory_write", "message_send", "code_exec", "browser_exec", "lifecycle", "admin"]
    action: str
    decision: Literal["ALLOW", "DENY", "REQUIRE_APPROVAL", "ALLOW_WITH_REDACTION"]
    reason: NotRequired[str]
    inputs_hash: str
    outputs_hash: str
    prev_hash: str
    hash: str


type AblDocument = dict[str, Any]


type PolicyDocument = dict[str, Any]


class PublishBlueprintVersionRequest(TypedDict):
    abl: AblDocument


class StartRunRequestBlueprint(TypedDict):
    name: str
    version: str


class StartRunRequest(TypedDict):
    blueprint: StartRunRequestBlueprint
    input: NotRequired[dict[str, Any]]


class SignalRunRequest(TypedDict):
    pid: NotRequired[Pid]
    signal: Signal
    reason: NotRequired[str]


class SignalRunResponse(TypedDict):
    pid: Pid
    state: ProcessState


class ListRunEventsResponse(TypedDict):
    items: list[RunEvent]
    next_cursor: NotRequired[str | None]


class DecideApprovalRequest(TypedDict):
    decision: Literal["approve", "reject"]
    comment: NotRequired[str]


class PublishPolicyPackRequest(TypedDict):
    policy: PolicyDocument


class TestPolicyRequestRequest(TypedDict):
    enforcement_point: str
    action: NotRequired[str]
    context: dict[str, Any]


class TestPolicyRequest(TypedDict):
    policy: PolicyDocument
    request: TestPolicyRequestRequest


class ListAuditEventsResponse(TypedDict):
    items: list[AuditEvent]
    next_cursor: NotRequired[str | None]


class VerifyAuditChainRequest(TypedDict):
    from_seq: NotRequired[int]
    to_seq: NotRequired[int]


class VerifyAuditChainResponse(TypedDict):
    ok: bool
    verified: int
    broken_at_seq: NotRequired[int]
    reason: NotRequired[str]


class ListKillSwitchesResponse(TypedDict):
    items: list[KillSwitch]


class GetUsageResponseItemsItem(TypedDict):
    meter: Meter
    quantity: float
    unit: str
    group: NotRequired[str]


class GetUsageResponse(TypedDict):
    items: list[GetUsageResponseItemsItem]


class StartEvalRunRequestBlueprint(TypedDict):
    name: str
    version: str
    namespace: NotRequired[str]


class StartEvalRunRequest(TypedDict):
    suite: str
    mode: NotRequired[Literal["ci", "manual"]]
    blueprint: StartEvalRunRequestBlueprint


class GetEvalRunComparisonResponse(TypedDict):
    comparison: NotRequired[EvalComparison]


class GateEvalReleaseRequestSuitesItem(TypedDict):
    ref: str
    threshold: NotRequired[float]


class GateEvalReleaseRequest(TypedDict):
    blueprint: EvalBlueprintRef
    suites: NotRequired[list[GateEvalReleaseRequestSuitesItem]]


class ListEvalDatasetsResponse(TypedDict):
    items: list[EvalDataset]


class CreateEvalDatasetRequest(TypedDict):
    name: str
    description: NotRequired[str]
    phi: NotRequired[bool]
    cases: list[EvalCase]


class ListEvalSuitesResponse(TypedDict):
    items: list[EvalSuite]


class CreateEvalSuiteRequest(TypedDict):
    ref: str
    dataset_ref: str
    graders: list[EvalGrader]
    pass_threshold: float
    min_case_score: NotRequired[float | None]
    settings: NotRequired[dict[str, Any]]
    tolerance: NotRequired[float]
    required_for_release: NotRequired[bool]
    applies_to: NotRequired[list[str]]
    min_samples: NotRequired[int]
    max_age_days: NotRequired[int]
    regression_requires_significance: NotRequired[bool]
    alpha: NotRequired[float]


class ListEvalBaselinesResponse(TypedDict):
    items: list[EvalBaseline]


class SetEvalBaselineRequest(TypedDict):
    run_id: str


class ListEvalReviewTasksResponse(TypedDict):
    items: list[EvalReviewTask]


class GradeEvalReviewTaskRequest(TypedDict):
    score: float
    comment: str


class SkipEvalReviewTaskRequest(TypedDict):
    reason: str


class ListEvalSamplingConfigsResponse(TypedDict):
    items: list[EvalSamplingConfig]


class PutEvalSamplingConfigRequest(TypedDict):
    blueprint: str
    suite: str
    rate: float
    max_per_hour: int
    redaction: NotRequired[Literal["phi", "always"]]
    enabled: NotRequired[bool]
    alert_threshold: NotRequired[float | None]


class GetEvalOnlineSummaryResponse(TypedDict):
    items: list[EvalOnlineSummary]


class ListEvalRunnersResponse(TypedDict):
    items: list[EvalRunner]


class RegisterEvalRunnerRequest(TypedDict):
    description: NotRequired[str]


class ListRegistryNamespacesResponse(TypedDict):
    items: list[RegistryNamespace]


class ClaimRegistryNamespaceRequest(TypedDict):
    namespace: str


class ListRegistryKeysResponse(TypedDict):
    items: list[RegistryKey]


class AddRegistryKeyRequest(TypedDict):
    public_key: str


class PublishRegistryBlueprintRequest(TypedDict):
    abl: AblDocument
    signature: RegistrySignature
    provenance: DsseEnvelope


class ListRegistryVersionsResponse(TypedDict):
    items: list[RegistryVersion]


class YankRegistryVersionRequest(TypedDict):
    reason: str


class YankRegistryVersionResponse(TypedDict):
    ok: bool


class ListMarketplaceListingsResponse(TypedDict):
    items: list[MarketplaceListing]


class PreviewMarketplaceInstallRequest(TypedDict):
    namespace: str
    name: str
    range: str


class ListMarketplaceInstallsResponse(TypedDict):
    items: list[MarketplaceInstall]


class InstallMarketplaceListingRequest(TypedDict):
    namespace: str
    name: str
    version: str
    content_hash: str
    consent_digest: str


class UninstallMarketplaceListingResponse(TypedDict):
    ok: bool
