import type { Framework, Row } from "./schema.js";
import { STATUSES } from "./schema.js";

const esc = (s: string): string => s.replaceAll("|", "\\|").replaceAll("\n", " ").trim();
const code = (s: string): string => `\`${s.replaceAll("`", "'")}\``;

const list = (xs: readonly string[]): string =>
  xs.length === 0 ? "none" : xs.map(code).join("<br>");

function rowBlock(r: Row): string[] {
  return [
    `### ${r.id}`,
    "",
    `- **Requirement (paraphrased):** ${r.requirement.trim()}`,
    `- **AXIS mechanism:** ${r.mechanism.trim()}`,
    `- **Code:** ${r.code.length === 0 ? "none" : r.code.map(code).join(", ")}`,
    `- **Config / flags:** ${r.config.length === 0 ? "none" : r.config.map(code).join(", ")}`,
    `- **Evidence:** ${r.evidence.length === 0 ? "none" : r.evidence.map((e) => `${e.kind}: ${code(e.ref)}`).join("; ")}`,
    `- **Status:** ${r.status}`,
    `- **Notes and limits:** ${r.notes.trim()}`,
    "",
  ];
}

/** Deterministic Markdown for one framework: a summary table (for reading) and one block per control (for reviewing). */
export function renderFramework(f: Framework, source: string): string {
  const counts = Object.fromEntries(
    STATUSES.map((s) => [s, f.rows.filter((r) => r.status === s).length]),
  );
  const out = [
    `<!-- GENERATED from ${source} by \`make compliance-check ARGS=--write\`. Do not edit by hand. -->`,
    "",
    `# ${f.title}`,
    "",
    `> Designed for / evidence-ready. This matrix maps requirements to AXIS mechanisms and to evidence that exists in this repository. It is not a certification, an attestation or a statement of conformity.`,
    "",
    f.scope.trim(),
    "",
    `Matrix version ${f.version}. Rows: ${f.rows.length} (${STATUSES.map((s) => `${s} ${counts[s]}`).join(", ")}).`,
    "",
    "| id | requirement | status | evidence |",
    "| --- | --- | --- | --- |",
    ...f.rows.map(
      (r) =>
        `| ${r.id} | ${esc(r.requirement)} | ${r.status} | ${r.evidence.length === 0 ? "none" : esc(list(r.evidence.map((e) => e.ref)))} |`,
    ),
    "",
    "## Controls",
    "",
    ...f.rows.flatMap(rowBlock),
  ];
  return `${out.join("\n")}\n`;
}

export function renderSummary(
  frameworks: readonly Framework[],
  files: Record<string, string>,
): string {
  const out = [
    "<!-- GENERATED by `make compliance-check ARGS=--write`. Do not edit by hand. -->",
    "",
    "# Control matrix summary",
    "",
    "Designed for / evidence-ready. Counts are of matrix rows by status; `Built` requires a test, make target or audit query that exists in the repository (checked by `make compliance-check`).",
    "",
    "| framework | rows | Built | Prototype | Designed | Gap | detail |",
    "| --- | --- | --- | --- | --- | --- | --- |",
    ...frameworks.map((f) => {
      const c = (s: string): number => f.rows.filter((r) => r.status === s).length;
      return `| ${f.title} | ${f.rows.length} | ${c("Built")} | ${c("Prototype")} | ${c("Designed")} | ${c("Gap")} | [${files[f.framework] ?? f.framework}](${files[f.framework] ?? f.framework}) |`;
    }),
    "",
  ];
  return `${out.join("\n")}\n`;
}
