# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: axis/runtime/v1/gate.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'axis/runtime/v1/gate.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from axis_runtime._gen.axis.runtime.v1 import common_pb2 as axis_dot_runtime_dot_v1_dot_common__pb2
from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x61xis/runtime/v1/gate.proto\x12\x0f\x61xis.runtime.v1\x1a\x1c\x61xis/runtime/v1/common.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xa3\x02\n\x0f\x45valuateRequest\x12\x11\n\ttenant_id\x18\x01 \x01(\t\x12,\n\x05trace\x18\x02 \x01(\x0b\x32\x1d.axis.runtime.v1.TraceContext\x12%\n\x05\x61\x63tor\x18\x03 \x01(\x0b\x32\x16.axis.runtime.v1.Actor\x12\x30\n\tblueprint\x18\x04 \x01(\x0b\x32\x1d.axis.runtime.v1.BlueprintRef\x12<\n\x11\x65nforcement_point\x18\x05 \x01(\x0e\x32!.axis.runtime.v1.EnforcementPoint\x12\x0e\n\x06\x61\x63tion\x18\x06 \x01(\t\x12(\n\x07\x63ontext\x18\x07 \x01(\x0b\x32\x17.google.protobuf.Struct\"\xc5\x01\n\x10\x45valuateResponse\x12+\n\x08\x64\x65\x63ision\x18\x01 \x01(\x0e\x32\x19.axis.runtime.v1.Decision\x12\x16\n\x0epolicy_version\x18\x02 \x01(\t\x12\x0e\n\x06reason\x18\x03 \x01(\t\x12\x18\n\x10matched_rule_ids\x18\x04 \x03(\t\x12\x15\n\rredact_fields\x18\x05 \x03(\t\x12\x13\n\x0b\x61pproval_id\x18\x06 \x01(\t\x12\x16\n\x0e\x61udit_event_id\x18\x07 \x01(\t\"\xfb\x01\n\x14SetKillSwitchRequest\x12\x11\n\ttenant_id\x18\x01 \x01(\t\x12:\n\x05scope\x18\x02 \x01(\x0e\x32+.axis.runtime.v1.SetKillSwitchRequest.Scope\x12\x0e\n\x06target\x18\x03 \x01(\t\x12\x0f\n\x07\x65ngaged\x18\x04 \x01(\x08\x12\x0e\n\x06reason\x18\x05 \x01(\t\"c\n\x05Scope\x12\x15\n\x11SCOPE_UNSPECIFIED\x10\x00\x12\x10\n\x0cSCOPE_GLOBAL\x10\x01\x12\x10\n\x0cSCOPE_TENANT\x10\x02\x12\x0f\n\x0bSCOPE_AGENT\x10\x03\x12\x0e\n\nSCOPE_TOOL\x10\x04\"@\n\x15SetKillSwitchResponse\x12\x0f\n\x07\x65ngaged\x18\x01 \x01(\x08\x12\x16\n\x0e\x61udit_event_id\x18\x02 \x01(\t2\xbe\x01\n\x0bGateService\x12O\n\x08\x45valuate\x12 .axis.runtime.v1.EvaluateRequest\x1a!.axis.runtime.v1.EvaluateResponse\x12^\n\rSetKillSwitch\x12%.axis.runtime.v1.SetKillSwitchRequest\x1a&.axis.runtime.v1.SetKillSwitchResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'axis.runtime.v1.gate_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EVALUATEREQUEST']._serialized_start=108
  _globals['_EVALUATEREQUEST']._serialized_end=399
  _globals['_EVALUATERESPONSE']._serialized_start=402
  _globals['_EVALUATERESPONSE']._serialized_end=599
  _globals['_SETKILLSWITCHREQUEST']._serialized_start=602
  _globals['_SETKILLSWITCHREQUEST']._serialized_end=853
  _globals['_SETKILLSWITCHREQUEST_SCOPE']._serialized_start=754
  _globals['_SETKILLSWITCHREQUEST_SCOPE']._serialized_end=853
  _globals['_SETKILLSWITCHRESPONSE']._serialized_start=855
  _globals['_SETKILLSWITCHRESPONSE']._serialized_end=919
  _globals['_GATESERVICE']._serialized_start=922
  _globals['_GATESERVICE']._serialized_end=1112
# @@protoc_insertion_point(module_scope)
