# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from axis_runtime._gen.axis.runtime.v1 import gate_pb2 as axis_dot_runtime_dot_v1_dot_gate__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in axis/runtime/v1/gate_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GateServiceStub:
    """The Risk Kernel. Every external action is evaluated here *before* execution.
    Clients MUST treat transport errors, deadlines and DECISION_UNSPECIFIED as DENY.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Evaluate = channel.unary_unary(
                '/axis.runtime.v1.GateService/Evaluate',
                request_serializer=axis_dot_runtime_dot_v1_dot_gate__pb2.EvaluateRequest.SerializeToString,
                response_deserializer=axis_dot_runtime_dot_v1_dot_gate__pb2.EvaluateResponse.FromString,
                _registered_method=True)
        self.SetKillSwitch = channel.unary_unary(
                '/axis.runtime.v1.GateService/SetKillSwitch',
                request_serializer=axis_dot_runtime_dot_v1_dot_gate__pb2.SetKillSwitchRequest.SerializeToString,
                response_deserializer=axis_dot_runtime_dot_v1_dot_gate__pb2.SetKillSwitchResponse.FromString,
                _registered_method=True)


class GateServiceServicer:
    """The Risk Kernel. Every external action is evaluated here *before* execution.
    Clients MUST treat transport errors, deadlines and DECISION_UNSPECIFIED as DENY.
    """

    def Evaluate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetKillSwitch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GateServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Evaluate': grpc.unary_unary_rpc_method_handler(
                    servicer.Evaluate,
                    request_deserializer=axis_dot_runtime_dot_v1_dot_gate__pb2.EvaluateRequest.FromString,
                    response_serializer=axis_dot_runtime_dot_v1_dot_gate__pb2.EvaluateResponse.SerializeToString,
            ),
            'SetKillSwitch': grpc.unary_unary_rpc_method_handler(
                    servicer.SetKillSwitch,
                    request_deserializer=axis_dot_runtime_dot_v1_dot_gate__pb2.SetKillSwitchRequest.FromString,
                    response_serializer=axis_dot_runtime_dot_v1_dot_gate__pb2.SetKillSwitchResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'axis.runtime.v1.GateService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('axis.runtime.v1.GateService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GateService:
    """The Risk Kernel. Every external action is evaluated here *before* execution.
    Clients MUST treat transport errors, deadlines and DECISION_UNSPECIFIED as DENY.
    """

    @staticmethod
    def Evaluate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/axis.runtime.v1.GateService/Evaluate',
            axis_dot_runtime_dot_v1_dot_gate__pb2.EvaluateRequest.SerializeToString,
            axis_dot_runtime_dot_v1_dot_gate__pb2.EvaluateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetKillSwitch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/axis.runtime.v1.GateService/SetKillSwitch',
            axis_dot_runtime_dot_v1_dot_gate__pb2.SetKillSwitchRequest.SerializeToString,
            axis_dot_runtime_dot_v1_dot_gate__pb2.SetKillSwitchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
