# Generated by @axis/policy. DO NOT EDIT.
# Sources: baseline-deny@1.0.0,phi-redaction@1.1.0
package axis.policy

import rego.v1

policy_version := "baseline-deny@1.0.0,phi-redaction@1.1.0"

decision_rank := {"DENY": 4, "REQUIRE_APPROVAL": 3, "ALLOW_WITH_REDACTION": 2, "ALLOW": 1}

gates := {"baseline-deny/amount-cap": {"id": "baseline-deny/amount-cap", "params": {"field": "args.amount", "max": 10000}, "type": "amount_cap"}, "baseline-deny/daily-spend": {"id": "baseline-deny/daily-spend", "params": {"hard": 100, "metric": "cost_usd", "soft": 80, "window": "day"}, "type": "budget"}, "baseline-deny/fire-rate": {"id": "baseline-deny/fire-rate", "params": {"key": "agent", "max": 30, "windowSeconds": 60}, "type": "rate_limit"}, "baseline-deny/fresh-quote": {"id": "baseline-deny/fresh-quote", "params": {"field": "args.quote_ts", "maxAgeSeconds": 5}, "type": "staleness"}, "baseline-deny/tenant-kill": {"id": "baseline-deny/tenant-kill", "params": {}, "scope": "tenant", "type": "kill_switch"}, "baseline-deny/venue-cap": {"id": "baseline-deny/venue-cap", "params": {"field": "args.venue", "max": 50000, "perTarget": true}, "type": "target_cap"}}

rules := {"baseline-deny/allow-read-tools": {"approval": null, "decision": "ALLOW", "gates": ["baseline-deny/tenant-kill", "baseline-deny/fire-rate"], "priority": 100, "redact": []}, "baseline-deny/approve-large-payments": {"approval": {"escalate_to": ["finance-director"], "on_timeout": "DENY", "roles": ["finance-approver"], "sla_seconds": 900}, "decision": "REQUIRE_APPROVAL", "gates": ["baseline-deny/tenant-kill", "baseline-deny/amount-cap"], "priority": 200, "redact": []}, "baseline-deny/deny-browser-offlist": {"approval": null, "decision": "DENY", "gates": [], "priority": 500, "redact": []}, "baseline-deny/redact-phi-egress": {"approval": null, "decision": "ALLOW_WITH_REDACTION", "gates": [], "priority": 100, "redact": ["phi.mrn", "phi.ssn", "pii.email"]}, "phi-redaction/allow-model-calls": {"approval": null, "decision": "ALLOW", "gates": [], "priority": 100, "redact": []}, "phi-redaction/deny-phi-to-code": {"approval": null, "decision": "DENY", "gates": [], "priority": 400, "redact": []}, "phi-redaction/redact-phi-egress": {"approval": null, "decision": "ALLOW_WITH_REDACTION", "gates": [], "priority": 300, "redact": ["phi.mrn", "phi.ssn", "pii.email"]}}

# --- pack baseline-deny@1.0.0
default c0_0 := false
default c0_1 := false
c0_1 if { v := input.tool.side_effects; v in ["none", "read"] }

c0_0 if {
	c0_1
}

matched contains "baseline-deny/allow-read-tools" if {
	input.enforcement_point in ["tool_call", "mcp_call"]
	c0_0
}

default c1_2 := false
default c1_3 := false
c1_3 if { input.tool.name == "payments" }

default c1_4 := false
c1_4 if { v := input.args.amount; is_number(v); v > 1000 }

c1_2 if {
	c1_3
	c1_4
}

matched contains "baseline-deny/approve-large-payments" if {
	input.enforcement_point in ["tool_call"]
	c1_2
}

default c2_5 := false
c2_5 if { input.data.phi == true }

matched contains "baseline-deny/redact-phi-egress" if {
	input.enforcement_point in ["model_call", "message_send"]
	c2_5
}

default c3_6 := false
default c3_7 := false
c3_7 if { v := input.args.domain; v in ["example.com", "docs.example.com"] }

c3_6 if { not c3_7 }

matched contains "baseline-deny/deny-browser-offlist" if {
	input.enforcement_point in ["browser_exec"]
	c3_6
}

# --- pack phi-redaction@1.1.0
default c4_0 := false
c4_0 if { input.data.phi == true }

matched contains "phi-redaction/redact-phi-egress" if {
	input.enforcement_point in ["model_call", "message_send"]
	c4_0
}

default c5_1 := false
c5_1 if { input.data.phi == true }

matched contains "phi-redaction/deny-phi-to-code" if {
	input.enforcement_point in ["code_exec", "browser_exec"]
	c5_1
}

default c6_2 := false
c6_2 if { input.data.phi != true }

matched contains "phi-redaction/allow-model-calls" if {
	input.enforcement_point in ["model_call", "message_send"]
	c6_2
}

# --- resolution: highest priority, then most restrictive decision
candidates := {id | some id in matched}

top_priority := max({rules[id].priority | some id in candidates}) if count(candidates) > 0

top := {id | some id in candidates; rules[id].priority == top_priority}

top_rank := max({decision_rank[rules[id].decision] | some id in top}) if count(candidates) > 0

winners := {id | some id in top; decision_rank[rules[id].decision] == top_rank}

winner_ids := sort(winners)

default result := {
	"decision": "DENY",
	"reason": "no matching rule (default deny)",
	"matched": [],
	"winners": [],
	"gates": [],
	"redact": [],
	"approval": null,
	"policy_version": "baseline-deny@1.0.0,phi-redaction@1.1.0",
}

result := {
	"decision": rules[winner_ids[0]].decision,
	"reason": concat(", ", winner_ids),
	"matched": sort(candidates),
	"winners": winner_ids,
	"gates": [gates[g] | some g in sort({g | some id in winners; some g in rules[id].gates})],
	"redact": sort({x | some id in winners; some x in rules[id].redact}),
	"approval": rules[winner_ids[0]].approval,
	"policy_version": policy_version,
} if count(candidates) > 0
