# Generated by @axis/policy. DO NOT EDIT.
# Sources: baseline-deny@1.0.0,phi-redaction@1.1.0
package axis.policy

import rego.v1

policy_version := "baseline-deny@1.0.0,phi-redaction@1.1.0"

decision_rank := {"DENY": 4, "REQUIRE_APPROVAL": 3, "ALLOW_WITH_REDACTION": 2, "ALLOW": 1}

gates := {"baseline-deny/amount-cap": {"id": "baseline-deny/amount-cap", "params": {"field": "args.amount", "max": 10000}, "type": "amount_cap"}, "baseline-deny/daily-spend": {"id": "baseline-deny/daily-spend", "params": {"hard": 100, "metric": "cost_usd", "soft": 80, "window": "day"}, "type": "budget"}, "baseline-deny/fire-rate": {"id": "baseline-deny/fire-rate", "params": {"key": "agent", "max": 30, "windowSeconds": 60}, "type": "rate_limit"}, "baseline-deny/fresh-quote": {"id": "baseline-deny/fresh-quote", "params": {"field": "args.quote_ts", "maxAgeSeconds": 5}, "type": "staleness"}, "baseline-deny/tenant-kill": {"id": "baseline-deny/tenant-kill", "params": {}, "scope": "tenant", "type": "kill_switch"}, "baseline-deny/venue-cap": {"id": "baseline-deny/venue-cap", "params": {"field": "args.amount", "max": 50000, "perTarget": true}, "type": "target_cap"}}

rules := {"baseline-deny/allow-read-tools": {"approval": null, "decision": "ALLOW", "gates": ["baseline-deny/tenant-kill", "baseline-deny/fire-rate"], "priority": 100, "redact": []}, "baseline-deny/approve-large-payments": {"approval": {"escalate_to": ["finance-director"], "on_timeout": "DENY", "roles": ["finance-approver"], "sla_seconds": 900}, "decision": "REQUIRE_APPROVAL", "gates": ["baseline-deny/tenant-kill", "baseline-deny/amount-cap"], "priority": 200, "redact": []}, "baseline-deny/deny-browser-offlist": {"approval": null, "decision": "DENY", "gates": [], "priority": 500, "redact": []}, "baseline-deny/redact-phi-egress": {"approval": null, "decision": "ALLOW_WITH_REDACTION", "gates": [], "priority": 100, "redact": ["phi.mrn", "phi.ssn", "pii.email"]}, "phi-redaction/allow-model-calls": {"approval": null, "decision": "ALLOW", "gates": [], "priority": 100, "redact": []}, "phi-redaction/deny-phi-to-code": {"approval": null, "decision": "DENY", "gates": [], "priority": 400, "redact": []}, "phi-redaction/redact-phi-egress": {"approval": null, "decision": "ALLOW_WITH_REDACTION", "gates": [], "priority": 300, "redact": ["phi.mrn", "phi.ssn", "pii.email"]}}

# --- pack baseline-deny@1.0.0
default t0_0 := false
default p0_0 := false
default t0_1 := false
default p0_1 := false
k0_1 if { _ := input.tool.side_effects }
t0_1 if { v := input.tool.side_effects; v in ["none", "read"] }
p0_1 if { t0_1 }
p0_1 if { not k0_1 }

t0_0 if {
	t0_1
}
p0_0 if {
	p0_1
}

matched contains "baseline-deny/allow-read-tools" if {
	input.enforcement_point in ["tool_call", "mcp_call"]
	t0_0
}

default t1_2 := false
default p1_2 := false
default t1_3 := false
default p1_3 := false
k1_3 if { _ := input.tool.name }
t1_3 if { v := input.tool.name; v == "payments" }
p1_3 if { t1_3 }
p1_3 if { not k1_3 }

default t1_4 := false
default p1_4 := false
k1_4 if { v := input.args.amount; is_number(v) }
t1_4 if { v := input.args.amount; is_number(v); v > 1000 }
p1_4 if { t1_4 }
p1_4 if { not k1_4 }

t1_2 if {
	t1_3
	t1_4
}
p1_2 if {
	p1_3
	p1_4
}

matched contains "baseline-deny/approve-large-payments" if {
	input.enforcement_point in ["tool_call"]
	t1_2
}

default t2_5 := false
default p2_5 := false
k2_5 if { _ := input.data.phi }
t2_5 if { v := input.data.phi; v == true }
p2_5 if { t2_5 }
p2_5 if { not k2_5 }

matched contains "baseline-deny/redact-phi-egress" if {
	input.enforcement_point in ["model_call", "message_send"]
	t2_5
}

default t3_6 := false
default p3_6 := false
default t3_7 := false
default p3_7 := false
k3_7 if { _ := input.args.domain }
t3_7 if { v := input.args.domain; v in ["example.com", "docs.example.com"] }
p3_7 if { t3_7 }
p3_7 if { not k3_7 }

t3_6 if { not p3_7 }
p3_6 if { not t3_7 }

matched contains "baseline-deny/deny-browser-offlist" if {
	input.enforcement_point in ["browser_exec"]
	p3_6
}

# --- pack phi-redaction@1.1.0
default t4_0 := false
default p4_0 := false
k4_0 if { _ := input.data.phi }
t4_0 if { v := input.data.phi; v == true }
p4_0 if { t4_0 }
p4_0 if { not k4_0 }

matched contains "phi-redaction/redact-phi-egress" if {
	input.enforcement_point in ["model_call", "message_send"]
	t4_0
}

default t5_1 := false
default p5_1 := false
k5_1 if { _ := input.data.phi }
t5_1 if { v := input.data.phi; v == true }
p5_1 if { t5_1 }
p5_1 if { not k5_1 }

matched contains "phi-redaction/deny-phi-to-code" if {
	input.enforcement_point in ["code_exec", "browser_exec"]
	p5_1
}

default t6_2 := false
default p6_2 := false
k6_2 if { _ := input.data.phi }
t6_2 if { v := input.data.phi; v != true }
p6_2 if { t6_2 }
p6_2 if { not k6_2 }

matched contains "phi-redaction/allow-model-calls" if {
	input.enforcement_point in ["model_call", "message_send"]
	t6_2
}

# --- resolution: highest priority, then most restrictive decision
candidates := {id | some id in matched}

top_priority := max({rules[id].priority | some id in candidates}) if count(candidates) > 0

top := {id | some id in candidates; rules[id].priority == top_priority}

top_rank := max({decision_rank[rules[id].decision] | some id in top}) if count(candidates) > 0

winners := {id | some id in top; decision_rank[rules[id].decision] == top_rank}

winner_ids := sort(winners)

default result := {
	"decision": "DENY",
	"reason": "no matching rule (default deny)",
	"matched": [],
	"winners": [],
	"gates": [],
	"redact": [],
	"approval": null,
	"policy_version": "baseline-deny@1.0.0,phi-redaction@1.1.0",
}

result := {
	"decision": rules[winner_ids[0]].decision,
	"reason": concat(", ", winner_ids),
	"matched": sort(candidates),
	"winners": winner_ids,
	"gates": [gates[g] | some g in sort({g | some id in winners; some g in rules[id].gates})],
	"redact": sort({x | some id in winners; some x in rules[id].redact}),
	"approval": rules[winner_ids[0]].approval,
	"policy_version": policy_version,
} if count(candidates) > 0
