#!/usr/bin/env bash
# Regenerate Python gRPC stubs from /proto into runtime/src/axis_runtime/_gen.
# Generated code is committed; never hand-edit it. Run from anywhere.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
OUT="$ROOT/runtime/src/axis_runtime/_gen"
rm -rf "$OUT"
mkdir -p "$OUT"
cd "$ROOT"
uv run --package axis-runtime python -m grpc_tools.protoc \
  -I proto \
  --python_out="$OUT" --pyi_out="$OUT" --grpc_python_out="$OUT" \
  proto/axis/runtime/v1/common.proto proto/axis/runtime/v1/gate.proto
# protoc emits absolute imports rooted at `axis.`; rewrite them to the package-local path.
find "$OUT" \( -name '*.py' -o -name '*.pyi' \) -print0 | xargs -0 sed -i \
  -e 's/^from axis\.runtime\.v1 import/from axis_runtime._gen.axis.runtime.v1 import/' \
  -e 's/^import axis\.runtime\.v1/import axis_runtime._gen.axis.runtime.v1/'
for d in "$OUT" "$OUT/axis" "$OUT/axis/runtime" "$OUT/axis/runtime/v1"; do
  [ -f "$d/__init__.py" ] || printf '"""GENERATED by runtime/scripts/gen_proto.sh - do not edit."""\n' > "$d/__init__.py"
done
echo "generated into $OUT"
